### ISSUE TITLE
Not working Raspberry Pi 5 Fresh 64 Bit Install

### ISSUE THREAD

**Issue by lesreaper** [luxonis/depthai-viewer#48] opened 2024-03-13 05:56 UTC
Used the new 64 bit install from Luxonis, fresh. Tried with two cameras. Oak-D-Pro W OV9782 and Oak-D-Pro.

Installed virtualenv as per the[ instructions here](https://customers.pyimagesearch.com/raspberry-pi-setup-instructions/) to setup a virtual environment.

In my virtual environment, installed `depthai-viewer` with:
```
pip install depthai-viewer
```
Successful install. Ran the app with `depthai-viewer` and got this error.

```
[2024-03-13T05:31:52Z ERROR wgpu::backend::direct] Error in Adapter::request_device: Limit 'max_texture_dimension_2d' value 8192 is better than allowed 4096
[2024-03-13T05:31:52Z ERROR eframe::native::run] Exiting because of error: Wgpu(RequestDeviceError(RequestDeviceError)) on event Resumed
Traceback (most recent call last):
  File "/home/pi/.local/bin/.virtualenvs/luxonis/bin/depthai-viewer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/.local/bin/.virtualenvs/luxonis/lib/python3.11/site-packages/depthai_viewer/__main__.py", line 27, in main
    sys.exit(bindings.main(sys.argv, python_exe, site_packages_directory))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: WGPU error: Requesting a device failed -> Requesting a device failed
```
I verify the camera is being seen with `lsusb` here:
```
Bus 001 Device 004: ID 03e7:2485 Intel Movidius MyriadX
```

**Comment by zrezke** [comment] 2024-03-14 10:46
Thanks for reporting and sorry for the inconvenience, I see what the problem is here. On RPI `max_texture_dimensions_2d` should be 4096, but we have it set to 8192. Will ship a fix for this soon.

**Comment by zrezke** [comment] 2024-03-14 12:56
Fixed https://github.com/luxonis/depthai-viewer/pull/50..
Will be included in the next release end of this week.

**Closed by zrezke** 2024-03-14 12:56 UTC
Labels: 🪳 bug, 👀 needs triage
